services:
  fastapi:
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_HOST=mongodb://mongodb:27017
  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - 27017:27017
    volumes:
      - /bitnami/mongodb
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /mosquitto/config
      - /mosquitto/data
      - /mosquitto/log
volumes:
