name: NVC Deployment Action

on:
  push:
    branches: [main]

jobs:
  depoly:
    runs-on: ubuntu-latest
    steps:
      - name: Build and deploy application container to Okteto  Namespace
        uses: addnab/docker-run-action@v3
        with:
          image: okteto/okteto:latest
          run: |
            okteto context use --token=${{ secrets.OKTETO_TOKEN }} --namespace=amjed-ali-k
            okteto deploy --build --wait
