name: NVC Deployment Action

on:
  push:
    branches: [main]

jobs:
  depoly:
    runs-on: ubuntu-latest
    steps:
      - uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Build and deploy application container to Okteto  Namespace
        uses: okteto/okteto:latest
        env: OKTETO_ORIGIN github_action
        run: |
          okteto deploy --build --wait
