name: NVC Deployment Action

on:
  push:
    branches: [main]

jobs:
  depoly:
    runs-on: ubuntu-latest
    steps:
      - uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - uses: okteto/namespace@latest
        with:
          namespace: amjed-ali-k

      - name: Build and deploy application container to Okteto  Namespace
        if: ${{ github.event_name == 'push' }}
        uses: okteto/deploy-stack@latest
        with:
          name: nvc-server
          build: false
          file: ./okteto-stack.yaml
