name: NVC Deployment Action

on:
  push:
    branches: [main]

jobs:
  depoly:
    runs-on: ubuntu-latest
    steps:
      - uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Build and deploy application container to Okteto  Namespace
        uses: addnab/docker-run-action@v3
        with:
          image: okteto/okteto:latest
          run: |
            okteto deploy --build --wait
