name: NVC Deployment Action

on:
  push:
    branches: [other]

jobs:
  depoly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set context to Okteto Cloud
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      - name: Build and deploy application container to Okteto Flask Namespace
        if: ${{ github.event_name == 'push' }}
        uses: amjed-ali-k/deploy-stack@v0.0.2
        with:
          name: amjed-ali-k
          build: true
